# -*- mode: ruby -*-
# vi: set ft=ruby :

# Many comments ommitted for brevity

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/focal64"
  
  # Define a VM name (as opposed to 'default') - for vagrant machine and VirtualBox gui
  config.vm.define "helloWorld"
  
  # Set hostname inside the VM
  config.vm.hostname = "helloWorld"
  
  # Default shared folder setting
  config.vm.synced_folder ".", "/vagrant"

  # Forward host's port 8080 to server's port 80
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  # Create a local file with content
  config.vm.provision "shell", inline: "echo 'Hello World!' > /vagrant/hello.txt"
  
  # Start a python simple web server
  config.vm.provision "shell", inline: "sudo python3 -m http.server 80 &"

end